TheCastle worker
PRX/Infrastructure pull request #586
Opened 2022-02-21 18:13 UTC by kookster

Added to `the-castle.yml` the def for a worker task that can run hourly.
Moved the EFS volume from the web service to the worker which needs it.
Updated parent stacks for additional param, and for having real ecr and secrets values for the new app stack

2022-02-21 19:13 UTC, farski approved these changes
I think that's looking pretty good

2022-02-21 22:09 UTC, farski commented on stacks/apps/the-castle.yml
>      Default: 8000
This may need to be 3000

2022-02-21 22:10 UTC, kookster commented on stacks/apps/the-castle.yml
>      Default: 8000
I think you're right

2022-02-21 22:12 UTC, kookster commented on stacks/apps/the-castle.yml
>      Default: 8000
fixed

2022-02-21 22:18 UTC, farski reviewed
L69 needs a real path to health check

2022-02-22 14:52 UTC, farski requested changes
I would keep everything as `TheCastle`, except for the secrets version parameter in the root stack (and the root stack only)

2022-02-22 17:10 UTC, farski approved these changes
Possibly the web task needs more memory, but otherwise this 👍

2022-02-22 17:33 UTC, merged