Feat/tag augury logged error alarms
PRX/Infrastructure pull request #670
Opened 2023-01-25 15:44 UTC by svevang

Fixes up the previous #669 

This:

- adds the tags to the "logged errors" alarms
- reformats so the metric filters, alarms and tags are cuddled together

2023-01-25 16:01 UTC, farski requested changes

2023-01-25 16:01 UTC, farski commented on stacks/apps/augury.yml
> +  AuguryWorkerLoggedAlarmTags:
`AuguryWorkerLoggedErrorsAlarmTags`

2023-01-25 16:01 UTC, farski commented on stacks/apps/augury.yml
> +    Condition: EnableWorkers # See README
No condition on alarm

2023-01-25 16:01 UTC, farski commented on stacks/apps/augury.yml
> +  AugurySlowWorkerLoggedAlarmTags:
`AugurySlowWorkerLoggedErrorsAlarmTags`

2023-01-25 16:01 UTC, farski commented on stacks/apps/augury.yml
> +    Condition: EnableWorkers # See README
No condition on alarm

2023-01-25 16:35 UTC, svevang commented on stacks/apps/augury.yml
> +  AuguryWebLoggedAlarmTags:
Thank you for the review!   I looked at the other names and opted to drop "Augury" from these resources names.  It already is in the augury stack etc, so no need for the appname prefix.  And less typing to boot!

2023-01-25 16:38 UTC, svevang commented
In the end I'd like the slack alarms to link to the log files.  I think this PR gets us a bit closer.

It seems to get the reference to the log lines, I'd have to add one of these: https://github.com/PRX/Infrastructure/blob/ed1556a0b7cc6a64eb8ec4a372f2cf43f981306f/devops/tooling/chat-ops/cloudwatch-alarms/src/slack/log-groups.js#L11
 to the alarm resources.    Maybe?

2023-01-26 14:58 UTC, farski commented
Yes, as long as the namespace that an alarm belongs to is in that list and the alarm includes the `prx:ops:cloudwatch-log-group-name` tag with an appropriate value, the Slack messages will include a link to CloudWatch Logs Insights for the period the alarm covers. If you need to add any namespaces to that list, I wouldn't worry about a PR; just add them.

2023-01-27 14:11 UTC, farski requested changes

2023-01-27 14:11 UTC, farski commented on stacks/apps/augury.yml
> +  SlowWorkerLoggedAlarmTags:
`SlowWorkerLoggedErrorsAlarmTags`

2023-01-27 19:19 UTC, farski approved these changes

2023-01-27 19:27 UTC, merged